/*
 Copyright (c) 2003-2020, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.add("removeformat",{lang:"af,ar,az,bg,bn,bs,ca,cs,cy,da,de,de-ch,el,en,en-au,en-ca,en-gb,eo,es,es-mx,et,eu,fa,fi,fo,fr,fr-ca,gl,gu,he,hi,hr,hu,id,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,oc,pl,pt,pt-br,ro,ru,si,sk,sl,sq,sr,sr-latn,sv,th,tr,tt,ug,uk,vi,zh,zh-cn",icons:"removeformat",hidpi:!0,init:function(a){a.addCommand("removeFormat",CKEDITOR.plugins.removeformat.commands.removeformat);a.ui.addButton&&a.ui.addButton("RemoveFormat",{label:a.lang.removeformat.toolbar,command:"removeFormat",
toolbar:"cleanup,10"})}});
CKEDITOR.plugins.removeformat={commands:{removeformat:{exec:function(a){for(var h=a._.removeFormatRegex||(a._.removeFormatRegex=new RegExp("^(?:"+a.config.removeFormatTags.replace(/,/g,"|")+")$","i")),d=a._.removeAttributes||(a._.removeAttributes=a.config.removeFormatAttributes.split(",")),f=CKEDITOR.plugins.removeformat.filter,p=a.getSelection().getRanges().createIterator(),q=function(a){return a.type==CKEDITOR.NODE_ELEMENT},n=[],c;c=p.getNextRange();){var k=c.createBookmark();c=a.createRange();
c.setStartBefore(k.startNode);k.endNode&&c.setEndAfter(k.endNode);c.collapsed||c.enlarge(CKEDITOR.ENLARGE_ELEMENT);var e=c.createBookmark(),b=e.startNode,l=e.endNode,m=function(b){for(var c=a.elementPath(b),e=c.elements,d=1,g;(g=e[d])&&!g.equals(c.block)&&!g.equals(c.blockLimit);d++)h.test(g.getName())&&f(a,g)&&b.breakParent(g)};m(b);if(l)for(m(l),b=b.getNextSourceNode(!0,CKEDITOR.NODE_ELEMENT);b&&!b.equals(l);)if(b.isReadOnly()){if(b.getPosition(l)&CKEDITOR.POSITION_CONTAINS)break;b=b.getNext(q)}else m=
b.getNextSourceNode(!1,CKEDITOR.NODE_ELEMENT),"img"==b.getName()&&b.data("cke-realelement")||b.hasAttribute("data-cke-bookmark")||!f(a,b)||(h.test(b.getName())?b.remove(1):(b.removeAttributes(d),a.fire("removeFormatCleanup",b))),b=m;e.startNode.remove();e.endNode&&e.endNode.remove();c.moveToBookmark(k);n.push(c)}a.forceNextSelectionCheck();a.getSelection().selectRanges(n)}}},filter:function(a,h){for(var d=a._.removeFormatFilters||[],f=0;f<d.length;f++)if(!1===d[f](h))return!1;return!0}};
CKEDITOR.editor.prototype.addRemoveFormatFilter=function(a){this._.removeFormatFilters||(this._.removeFormatFilters=[]);this._.removeFormatFilters.push(a)};CKEDITOR.config.removeFormatTags="b,big,cite,code,del,dfn,em,font,i,ins,kbd,q,s,samp,small,span,strike,strong,sub,sup,tt,u,var";CKEDITOR.config.removeFormatAttributes="class,style,lang,width,height,align,hspace,valign";