CKEDITOR.dialog.add("interactionsourcedialog",function(d){function k(a,b){return a.replace(/\{\{(\w+)\}\}/g,function(a,e){return void 0!==b[e]?b[e]:a})}function l(a,b,c){CKEDITOR.plugins.get("alertdialog")?a.openDialog("alertdialog",function(a){a.setValueOf("info","msg",b);if(c)a.once("hide",c)}):(alert(b),c&&c())}function g(a,b){return a&&"function"===typeof a[b]}function h(a,b,c){c=c||"";if(g(a,"getAttribute"))try{var e=a.getAttribute(b);return null!==e?e:c}catch(d){}return c}function r(a){n();
if(!a||!g(a,"getName"))return null;if(d.interactionWrapper)return m(d.interactionWrapper,a);var b=g(a,"getParent")?a.getParent():null;return b&&p(b)?m(b,a):(b=t(a))?m(b,a):null}function m(a,b){var c=h(a,"class"),e=h(b,"data-serial");return{wrapper:a,placeholder:k(f.placeholderTemplate,{className:c,serialId:e||""})}}function p(a){if(!a)return!1;try{if(!g(a,"getName")||"div"!==a.getName()||h(a,"data-qti-class"))return!1;for(var b=h(a,"class",""),c=["col-","grid-row","qti-itemBody","item-editor-drop-area"],
e=0;e<c.length;e++)if(-1!==b.indexOf(c[e]))return!1;if(h(a,"data-units"))return!1;if(g(a,"hasClass")&&a.hasClass("custom-interaction-wrapper"))return!0;if(g(a,"getChildren"))for(var d=a.getChildren(),e=0;e<d.count();e++){var f=d.getItem(e);if(g(f,"getAttribute")&&(f.getAttribute("data-qti-class")||f.getAttribute("data-serial")&&0===f.getAttribute("data-serial").indexOf("interaction_")))return!0}return!1}catch(k){return!1}}function t(a){if(!g(a,"getParent"))return null;try{for(var b=5;a&&0<b;){var c=
a.getParent();if(p(c)&&(g(c,"hasClass")&&c.hasClass("custom-interaction-wrapper")||h(c,"class")&&!h(c,"data-serial")&&!h(c,"data-html-editable")))return c;a=c;b--}return null}catch(d){return console.error("Error in findClosestWrapperDiv:",d),null}}function n(){g(d,"findInteractionAndWrapper")&&d.findInteractionAndWrapper()}function u(a,b){var c=h(a,"data-serial"),c=c||"";return d.lastInteractionHasWrapper&&d.lastWrapperClass&&!b?k(f.placeholderTemplate,{className:d.lastWrapperClass,serialId:c}):b?
b.placeholder:k(f.simpleTemplate,{serialId:c})}var f={size:{width:Math.min(CKEDITOR.document.getWindow().getViewPaneSize().width-70,800),height:CKEDITOR.document.getWindow().getViewPaneSize().height/1.5},placeholderTemplate:'\x3cdiv class\x3d"{{className}}"\x3e\n\x3cinteraction_{{serialId}}\x3e\n\x3c/div\x3e',simpleTemplate:"\x3cinteraction_{{serialId}}\x3e",css:{wrapperInfo:"margin-bottom: 10px; padding: 5px; border-left: 3px solid #ccc; background-color: #f9f9f9;",example:"margin: 3px 0 0; color: #666; font-style: italic;",
codeBlock:"display: block; margin-top: 5px; padding: 5px; background: #f0f0f0; border: 1px solid #ddd; font-family: monospace;",textarea:"cursor:auto; width:100%; min-width:{{width}}px; max-width:unset; height:{{height}}px; tab-size:4; text-align:left; font-family:monospace;"}},q=null;return{title:d.lang.interactionsource.title,minWidth:600,minHeight:400,resizable:CKEDITOR.DIALOG_RESIZE_BOTH,onShow:function(){var a=this;n();var b=d.interactionElement;if(b)try{var c=r(b),e=u(b,c);this.setValueOf("main",
"data",e);q=e}catch(f){console.error("Error getting simplified interaction HTML:",f),l(d,"Error retrieving simplified interaction HTML: "+f.message),setTimeout(function(){a.hide()},0)}else l(d,"No interaction found or not currently editing an interaction."),setTimeout(function(){a.hide()},0)},onOk:function(){if(this.getValueOf("main","data").replace(/\r/g,"")===q)return!0;d.focus();try{var a=this.getValueOf("main","data");if(!a)throw Error("No edited data available");if(!d.interactionElement)throw Error("Interaction element not found.");
var b=CKEDITOR.htmlParser.fragment.fromHtml(a),c=1===b.children.length&&"div"===b.children[0].name;if(c){var e=b.children[0];d.lastWrapperClass=e.attributes&&e.attributes["class"]||""}d.lastInteractionHasWrapper=c;this.hide();d.fire("pluginContentModified",{html:a,pluginName:"interactionsourcedialog"})}catch(f){console.error("Error applying changes:",f),l(d,"Error updating interaction: "+f.message)}return!1},contents:[{id:"main",label:d.lang.interactionsource.title,elements:[{type:"html",id:"wrapperInfo",
html:function(){var a=d.lang.interactionsource;return'\x3cdiv id\x3d"interaction-wrapper-info" style\x3d"'+f.css.wrapperInfo+'"\x3e\x3cp style\x3d"'+f.css.example+'"\x3e'+a.wrapperExample+'\x3cbr\x3e\x3ccode style\x3d"'+f.css.codeBlock+'"\x3e\x26lt;div class\x3d"foobar"\x26gt;\x3cbr\x3e\x26nbsp;\x26nbsp;\x26lt;interaction_serial_number\x26gt;\x3cbr\x3e\x26lt;/div\x26gt;\x3c/code\x3e\x3c/p\x3e\x3cp style\x3d"'+f.css.example+'"\x3e\x3cem\x3e'+a.styleEditorNote+"\x3c/em\x3e\x3c/p\x3e\x3c/div\x3e"}()},
{type:"textarea",id:"data",dir:"ltr",inputStyle:k(f.css.textarea,f.size),"class":"cke_source"}]}]}});