/*
 Copyright (c) 2003-2020, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){CKEDITOR.plugins.add("taolanguage",{requires:"menubutton",lang:"ar,az,bg,ca,cs,cy,da,de,de-ch,el,en,en-au,en-gb,eo,es,es-mx,et,eu,fa,fi,fo,fr,gl,he,hr,hu,id,it,ja,km,ko,ku,lt,lv,nb,nl,no,oc,pl,pt,pt-br,ro,ru,sk,sl,sq,sr,sr-latn,sv,tr,tt,ug,uk,vi,zh,zh-cn",icons:"language",hidpi:!0,selectedLanguages:[],langLabels:{en:"English"},init:function(a){var b=a.config.language_list||["ar:Arabic:rtl","fr:French","es:Spanish"],c=this,d=a.lang.taolanguage,e={},f,h,k,g;b.forEach(function(a){a=a.split(":");
c.langLabels[a[0]]=a[1]});a.addCommand("language",{allowedContent:"span[!lang,!dir]",requiredContent:"span[lang,dir]",contextSensitive:!0,exec:function(a,b){var c=e["language_"+b];if(c)a[c.style.checkActive(a.elementPath(),a)?"removeStyle":"applyStyle"](c.style)},refresh:function(a){document.body.classList.remove("cke_panel_visible");a.element.addClass("cke_taolanguage_enabled");c.updateSelectedLanguages(a);c.updateButtonLabel(c.selectedLanguages,a.lang.taolanguage.button);this.setState(c.getCurrentLangElement(a)?
CKEDITOR.TRISTATE_ON:CKEDITOR.TRISTATE_OFF)}});for(g=0;g<b.length;g++)f=b[g].split(":"),h=f[0],k="language_"+h,e[k]={label:f[1],langId:h,group:"language",order:g,ltr:"rtl"!=(""+f[2]).toLowerCase(),className:"cke_menubutton__"+(""+f[2]).toLowerCase(),onClick:function(){a.execCommand("language",this.langId)},role:"menuitemcheckbox"},e[k].style=new CKEDITOR.style({element:"span",attributes:{lang:h,dir:e[k].ltr?"ltr":"rtl"}});e.language_remove={label:d.remove,group:"language_remove",state:CKEDITOR.TRISTATE_DISABLED,
order:e.length,className:"cke_menubutton__language_remove",onClick:function(){var b=c.getCurrentLangElement(a);b&&a.execCommand("language",b.getAttribute("lang"))}};a.addMenuGroup("language_remove",1);a.addMenuGroup("language");a.addMenuItems(e);a.ui.add("Language",CKEDITOR.UI_MENUBUTTON,{label:d.button,allowedContent:"span[!lang,!dir]",requiredContent:"span[lang,dir]",toolbar:"bidi,30",command:"language",className:"cke_button__taolanguage",onMenu:function(){document.body.classList.add("cke_panel_visible");
var b={},d=c.getCurrentLangElement(a),f;for(f in e)b[f]=CKEDITOR.TRISTATE_OFF;b.language_remove=d?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED;1===c.selectedLanguages.length&&d&&(b["language_"+d.getAttribute("lang")]=CKEDITOR.TRISTATE_ON);return b}});a.addRemoveFormatFilter&&a.addRemoveFormatFilter(function(a){return!(a.is("span")&&a.getAttribute("dir")&&a.getAttribute("lang"))})},getCurrentLangElement:function(a){var b=a.elementPath();a=b&&b.elements;var c;if(b)for(var d=0;d<a.length;d++)b=a[d],
!c&&"span"==b.getName()&&b.hasAttribute("dir")&&b.hasAttribute("lang")&&(c=b);return c},updateSelectedLanguages:function(a){var b=[];a.getSelectedHtml().find("[dir][lang]").$.forEach(function(a){-1===b.indexOf(a.getAttribute("lang"))&&b.push(a.getAttribute("lang"))});0===b.length&&(a=(a=this.getCurrentLangElement(a))&&a.getAttribute("lang"))&&b.push(a);this.selectedLanguages=b},updateButtonLabel:function(a,b){var c=1===a.length?this.langLabels[a[0]]:b;$(".cke_button__language_label").text(c)}})})();