/*
 Copyright (c) 2003-2015, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license

 Heavily modified for TAO usage
 @author Christophe Noël <christophe@taotesting.com>
*/
(function(){function r(a){for(var e=0,l=0,b=0,k,d=a.$.rows.length;b<d;b++){k=a.$.rows[b];for(var c=e=0,q,g=k.cells.length;c<g;c++)q=k.cells[c],e+=q.colSpan;e>l&&(l=e)}return l}function n(a){return function(){var e=this.getValue(),e=!!(CKEDITOR.dialog.validate.integer()(e)&&0<e);e||(alert(a),this.select());return e}}function p(a,e){var l=function(b){return new CKEDITOR.dom.element(b,a.document)};return{title:a.lang.table.title,minWidth:310,minHeight:CKEDITOR.env.ie?310:280,onShow:function(){var b,
k=this.getContentElement("info","txtRows"),d=this.getContentElement("info","txtCols");"taoqtitableProperties"===e&&(b=a.element.findOne("table"),this._.selectedElement=b);b?(this.setupContent(b),k&&k.disable(),d&&d.disable()):(k&&k.enable(),d&&d.enable())},onOk:function(){var b=a.getSelection(),k=this._.selectedElement&&b.createBookmarks(),d=this._.selectedElement||l("table"),c={};this.commitContent(c,d);if(c.info){var e=c.info;if(!this._.selectedElement)for(var g=d.append(l("tbody")),f=parseInt(e.txtRows,
10)||0,m=parseInt(e.txtCols,10)||0,c=0;c<f;c++)for(var h=g.append(l("tr")),n=0;n<m;n++)h.append(l("td")).appendBogus();e=e.selHeaders;if(!d.$.tHead&&("row"==e||"both"==e)){h=new CKEDITOR.dom.element(d.$.createTHead());g=d.getElementsByTag("tbody").getItem(0);g=g.getElementsByTag("tr").getItem(0);for(c=0;c<g.getChildCount();c++)f=g.getChild(c),f.type!=CKEDITOR.NODE_ELEMENT||f.data("cke-bookmark")||(f.renameNode("th"),f.setAttribute("scope","col"));h.append(g.remove())}if(null!==d.$.tHead&&"row"!=e&&
"both"!=e){h=new CKEDITOR.dom.element(d.$.tHead);g=d.getElementsByTag("tbody").getItem(0);for(m=g.getFirst();0<h.getChildCount();){g=h.getFirst();for(c=0;c<g.getChildCount();c++)f=g.getChild(c),f.type==CKEDITOR.NODE_ELEMENT&&(f.renameNode("td"),f.removeAttribute("scope"));g.insertBefore(m)}h.remove()}if(!this.hasColumnHeaders&&("col"==e||"both"==e))for(h=0;h<d.$.rows.length;h++)f=new CKEDITOR.dom.element(d.$.rows[h].cells[0]),f.renameNode("th"),f.setAttribute("scope","row");if(this.hasColumnHeaders&&
"col"!=e&&"both"!=e)for(c=0;c<d.$.rows.length;c++)h=new CKEDITOR.dom.element(d.$.rows[c]),"tbody"==h.getParent().getName()&&(f=new CKEDITOR.dom.element(h.$.cells[0]),f.renameNode("td"),f.removeAttribute("scope"))}if(this._.selectedElement)try{b.selectBookmarks(k)}catch(p){}else b=l("div"),b.setAttributes({"data-new":!0,"data-qti-class":"table","class":"widget-box"}),b.append(d),d=a.config.taoQtiItem,"function"===typeof d.insert&&(a.insertElement(b),d.insert.call(a,b.$))},contents:[{id:"info",label:"TAO QTI TABLE",
elements:[{type:"vbox",widths:[null,null],styles:["vertical-align:top"],children:[{type:"text",id:"txtRows","default":3,label:a.lang.table.rows,required:!0,controlStyle:"width:5em",validate:n(a.lang.table.invalidRows),setup:function(b){this.setValue(b.$.rows.length)},commit:m},{type:"text",id:"txtCols","default":2,label:a.lang.table.columns,required:!0,controlStyle:"width:5em",validate:n(a.lang.table.invalidCols),setup:function(b){this.setValue(r(b))},commit:m},{type:"html",html:"\x26nbsp;"},{type:"select",
id:"selHeaders",requiredContent:"th","default":"",label:a.lang.table.headers,items:[[a.lang.table.headersNone,""],[a.lang.table.headersRow,"row"],[a.lang.table.headersColumn,"col"],[a.lang.table.headersBoth,"both"]],setup:function(b){var a=this.getDialog();a.hasColumnHeaders=!0;for(var d=0;d<b.$.rows.length;d++){var c=b.$.rows[d].cells[0];if(c&&"th"!=c.nodeName.toLowerCase()){a.hasColumnHeaders=!1;break}}null!==b.$.tHead?this.setValue(a.hasColumnHeaders?"both":"row"):this.setValue(a.hasColumnHeaders?
"col":"")},commit:m},{type:"text",id:"txtCaption",requiredContent:"caption",label:a.lang.table.caption,setup:function(b){this.enable();b=b.getElementsByTag("caption");if(0<b.count()){b=b.getItem(0);var a=b.getFirst(CKEDITOR.dom.walker.nodeType(CKEDITOR.NODE_ELEMENT));a&&!a.equals(b.getBogus())?(this.disable(),this.setValue(b.getText())):(b=CKEDITOR.tools.trim(b.getText()),this.setValue(b))}},commit:function(b,e){if(this.isEnabled()){var d=this.getValue(),c=e.getElementsByTag("caption");if(d)0<c.count()?
(c=c.getItem(0),c.setHtml("")):(c=new CKEDITOR.dom.element("caption",a.document),e.getChildCount()?c.insertBefore(e.getFirst()):c.appendTo(e)),c.append(new CKEDITOR.dom.text(d,a.document));else if(0<c.count())for(d=c.count()-1;0<=d;d--)c.getItem(d).remove()}}}]}]}]}}var m=function(a){var e=this.id;a.info||(a.info={});a.info[e]=this.getValue()};CKEDITOR.dialog.add("taoqtitable",function(a){return p(a,"taoqtitable")});CKEDITOR.dialog.add("taoqtitableProperties",function(a){return p(a,"taoqtitableProperties")})})();