/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
(function(){function z(a){var h="left"==a?"pageXOffset":"pageYOffset";return h in k.$?k.$[h]:CKEDITOR.document.$.documentElement["left"==a?"scrollLeft":"scrollTop"]}function m(a){var h=a.config,f=h.floatSpace||{on:{}},x=!1,t=a.fire("uiSpace",{space:"top",html:""}).html,r=function(){function b(a,d,b){c.setStyle(d,y(b));c.setStyle("position",a)}function e(a){var g=n.getDocumentPosition();switch(a){case "top":b("absolute","top",g.y-u-v);break;case "pin":b("fixed","top",A);break;case "bottom":b("absolute",
"top",g.y+(d.height||d.bottom-d.top)+v)}f.on&&"function"===typeof f.on.changeMode&&f.on.changeMode.call(c.$,p,a);p=a}var p,n,q,d,l,u,m,t=h.floatSpaceDockedOffsetX||0,v=h.floatSpaceDockedOffsetY||0,w=h.floatSpacePinnedOffsetX||0,A=h.floatSpacePinnedOffsetY||0;return function(b){if(!n)if(f.centerElement){var g;g="function"===typeof f.centerElement?f.centerElement.call(null):f.centerElement;n=new CKEDITOR.dom.element(g);n.on("mousedown",function(a){a.data.preventDefault()})}else if(!(n=a.editable()))return;
x||(b&&"focus"===b.name&&c.show(),c.removeStyle("left"),c.removeStyle("right"),q=c.getClientRect(),d=n.getClientRect(),l=k.getViewPaneSize(),u=q.height,m=z("left"),p?(u+v<=d.top?e("top"):u+v>l.height-d.bottom?e("pin"):e("bottom"),b=l.width/2,b=0<d.left&&d.right<l.width&&d.width>q.width?"rtl"==a.config.contentsLangDirection?"right":"left":b-d.left>d.right-b?"left":"right",q.width>l.width?(b="left",g=0):(g="left"==b?0<d.left?d.left:0:d.right<l.width?l.width-d.right:0,g+q.width>l.width&&(b="left"==b?
"right":"left",g=0)),c.setStyle(b,y(("pin"==p?w:t)+g+("pin"==p?0:"left"==b?m:-m)))):(p="pin",e("pin"),r(b)))}}();if(t){var m=new CKEDITOR.template('\x3cdiv id\x3d"cke_{name}" class\x3d"cke {id} cke_reset_all cke_chrome cke_editor_{name} cke_float cke_{langDir} '+CKEDITOR.env.cssClass+'" dir\x3d"{langDir}" title\x3d"'+(CKEDITOR.env.gecko?" ":"")+'" lang\x3d"{langCode}" role\x3d"application" style\x3d"{style}" aria-labelledby\x3d"cke_{name}_arialbl"\x3e\x3cspan id\x3d"cke_{name}_arialbl" class\x3d"cke_voice_label"\x3e{voiceLabel}\x3c/span\x3e\x3cdiv class\x3d"cke_inner"\x3e\x3cdiv id\x3d"{topId}" class\x3d"cke_top" role\x3d"presentation"\x3e{content}\x3c/div\x3e\x3c/div\x3e\x3cspan class\x3d"cke_nose"\x3e\x3cspan\x3e\x3c/div\x3e'),
c=CKEDITOR.document.getBody().append(CKEDITOR.dom.element.createFromHtml(m.output({content:t,id:a.id,langDir:a.lang.dir,langCode:a.langCode,name:a.name,style:"display:none;z-index:"+(h.baseFloatZIndex-1),topId:a.ui.spaceId("top"),voiceLabel:a.lang.editorPanel+", "+a.name}))),w=CKEDITOR.tools.eventsBuffer(500,r),e=CKEDITOR.tools.eventsBuffer(100,r);c.unselectable();c.on("mousedown",function(a){a=a.data;a.getTarget().hasAscendant("a",1)||a.preventDefault()});a.on("focus",function(b){r(b);a.on("change",
w.input);k.on("scroll",e.input);k.on("resize",e.input)});a.on("blur",function(b){c.hide();a.removeListener("change",w.input);k.removeListener("scroll",e.input);k.removeListener("resize",e.input)});a.on("destroy",function(){k.removeListener("scroll",e.input);k.removeListener("resize",e.input);c.clearCustomData();c.remove()});a.focusManager.hasFocus&&c.show();a.focusManager.add(c,1);f.on&&"function"===typeof f.on.ready&&f.on.ready.call(c.$,{show:function(){x=!1;c.show();r()},hide:function(){c.hide();
x=!0}})}}var k=CKEDITOR.document.getWindow(),y=CKEDITOR.tools.cssLength;CKEDITOR.plugins.add("floatingspace",{init:function(a){a.on("loaded",function(){m(this)},null,null,20)}})})();